version: "2.1"

networks:
    extnetwork:
        name: chubaodb-extnetwork
        ipam:
            config:
                - subnet: 192.168.0.0/24
                  gateway: 192.168.0.1

services:
    build:
        image: ansj/chubaodb_base:1.6.3
        volumes:
            - ../:/rust/chubaodb
            - ~/.cargo/registry/:/root/.cargo/registry/
            - ~/.cargo/git/:/root/.cargo/git/
        command:
            - bash
            - "-c"
            - >-
                set -e;
                export LD_LIBRARY_PATH=/usr/local/lib;
                cd /rust/chubaodb;
                source ~/.cargo/env;
                cargo clean;
                echo "Build project...";
                cargo build --release;
                cp /rust/chubaodb/target/release/chubaodb /rust/chubaodb/docker/build/
        networks:
            extnetwork:
